### ISSUE TITLE
pyderasn.DecodeError: CPBlob remaining data

### ISSUE THREAD

**Issue by OstapW** [li0ard/cpfx#2]
При попытке выполнить декодировку pfx для эцп выпущенного тестовым УЦ КриптоПро падает с ошибкой:

CryptoPro PFX Decoder by li0ard
Введите пароль: 
 SALT  = 52259485af47d3c358c7ba66a74c37ed
 ITERS = 2000
Прогресс: |**************************************************| 100.0% Завершено
 KEY   = 27458cabecb90b08177d58b85b157ffe2b2ae8829dc3260590ebbecb633dbc7f
 IV    = 52259485af47d3c3
Traceback (most recent call last):
  File "cpfx.py", line 91, in <module>
    result = CPBlob().decode(result)[0]
  File "/usr/local/lib/python3.8/dist-packages/pyderasn-9.3-py3.8.egg/pyderasn.py", line 1922, in decode
  File "/usr/local/lib/python3.8/dist-packages/pyderasn-9.3-py3.8.egg/pyderasn.py", line 1966, in decode_evgen
  File "/usr/local/lib/python3.8/dist-packages/pyderasn-9.3-py3.8.egg/pyderasn.py", line 6609, in _decode
pyderasn.DecodeError: CPBlob remaining data

Файл приложил.
 [gost.pfx.zip](https://github.com/li0ard/cpfx/files/12353003/gost.pfx.zip)

**Comment by li0ard** [comment]
А пробовали в СКЗИ сначала импортировать, а потом попробовать экспортировать и уже этот PFX прогнать через прогу? Просто если так уже не прокатит значит КриптоПро опять что то намутил с форматом

**Comment by OstapW** [comment]
Это pfx эскпортированный из КриптоПро CryptCP 5.0

**Comment by li0ard** [comment]
А вот в чём собственно была проблема. КриптоПро добавил Attributes с OID 1.2.643.2.2.37.3.10 (aka szOID_CryptoPro_private_keys_extension_container_exchange_key_usage_period) в связи с чем библиотека PyDERASN видела лишнее поле (не описанное в схеме) и писала об этом

![image](https://github.com/li0ard/cpfx/assets/47205258/0b9a71c5-7eb0-49e8-8598-6a056fcb640d)

**Comment by li0ard** [comment]
Исправлено
