### ISSUE TITLE
добавить в справочную информацию как можно выгрузить ключ в pfx и т.п.

### ISSUE THREAD

**Issue by MaksimKlyu** [li0ard/cpfx#3]
Спасибо вам за проделанную работу!
Будьте добры, добавьте в справку, как можно выгрузить ключ в pfx и прочие ключевые действия.
https://identityblitz.ru/products/esia-bridge/documentation/

**Comment by li0ard** [comment]
Приветствую! А что сложного в экспортировании ключей через КриптоПро? В разделе "Сертификаты" выбрать нужный и нажать "Экспортировать ключи". Правда есть оговорка в том что ключ должен быть экспортируемым и не должен храниться на токене через механизм ФКН
