### ISSUE TITLE
Баг из pfx (импортированого из КриптоПро) в pem

### ISSUE THREAD

**Issue by ipoliashenko** [li0ard/cpfx#4]
File "/home/user/cash-api/cpfx/cpfx.py", line 92, in <module>
    result = CPBlob().decode(result)[0]
  File "/home/ipoliashenko/cash-api/cpfx/pyderasn.py", line 1922, in decode
    result = next(self.decode_evgen(
  File "/home/user/cash-api/cpfx/pyderasn.py", line 1966, in decode_evgen
    for result in self._decode(
  File "/home/user/cash-api/cpfx/pyderasn.py", line 6440, in _decode
    raise TagMismatch(
pyderasn.TagMismatch: CPBlob

**Comment by ipoliashenko** [comment]
зато отработало c тем же файлом только в формате p12

**Comment by li0ard** [comment]
Судя по ошибке проблема в экспорте криптопро, он в ключевой блоб что то не то записал

**Comment by ipoliashenko** [comment]
> Судя по ошибке проблема в экспорте криптопро, он в ключевой блоб что то не то записал

Выгрузил последний коммит ошибка ушла, но в проекте зависимости которые указаны не все есть в pip

**Comment by li0ard** [comment]
Да, официальной (от разработчика) версии pygost нету в pip, однако вы можете установить её с сайта разработчика http://pygost.cypherpunks.ru
